### ISSUE TITLE
New Docker Image gdb-multiarch

### ISSUE THREAD

**Issue by cwillforeal** [lukstep/raspberry-pi-pico-docker-sdk#10]
Hi,

Not sure this is the place to add this comment but I think the new docker image is missing gdb-multiarch install. I'm not super experienced with Docker but the output of the "latest" tag currently has nothing in "/usr/bin/gdg-multiarch".

Thanks for putting together these tools they've been super helpful!

**Comment by lukstep** [comment]
Hi, 

I'm very glad you use these tools and they are helpful to you ☺️.

I wanted to keep the SDK container image as small as possible. That's why I threw everything that's not needed for building out of the container. `gdb-multiarch` is installed in [devcontainer](https://github.com/lukstep/pico-template-project/blob/main/.devcontainer/devcontainer.json) which can be used for development.

If you don't use vscode you can create your own image based on `raspberry-pi-pico-sdk` or modify existing `Dockerfile` and rebuild image. (instruction [here](https://github.com/lukstep/raspberry-pi-pico-docker-sdk/tree/main?tab=readme-ov-file#building-the-image-and-running-the-container))
